### ISSUE TITLE
ffi ffj ligatures are broken

### ISSUE THREAD

**Issue by hyvyys** [Fonthausen/Livvic#4]
For f_f_i and f_f_j ligatures, the i/j component is missing.
![obraz](https://user-images.githubusercontent.com/20814638/63540031-9b315080-c51b-11e9-82b3-d4dca5945735.png)

**Comment by m4rc1e** [comment]
Thanks for reporting. I'll try and get this done next week.

**Comment by m4rc1e** [comment]
I think the ligatures are only broken on Google Fonts. I suspect GF is tampering with the font's OT features. I'll find a fix for this next week.

**Comment by hyvyys** [comment]
That sounds just about right. GF strips for example the mark feature which
is really lousy for languages that depend on it.

pt., 30 sie 2019, 16:58 użytkownik Marc Foley <notifications@github.com>
napisał:

**Comment by m4rc1e** [comment]
Fixes have now made it onto Google Fonts.

<img width="576" alt="Screenshot 2019-09-18 at 14 39 09" src="https://user-images.githubusercontent.com/7525512/65153684-19e9b280-da22-11e9-8253-6b441ef69253.png">

Thank you for your patience.

**Comment by hyvyys** [comment]
Awesome, thanks for the update.

śr., 18 wrz 2019 o 15:39 Marc Foley <notifications@github.com> napisał(a):

**Comment by davelab6** [comment]
I wonder if the `ff` ligature should have the same single/joined bar as the `ffi`?

<img width="99" alt="Screen Shot 2020-04-21 at 2 27 48 PM" src="https://user-images.githubusercontent.com/261579/79900541-60e6be80-83dc-11ea-95f6-7eb00b09e66a.png">


<img width="106" alt="Screen Shot 2020-04-21 at 2 27 52 PM" src="https://user-images.githubusercontent.com/261579/79900540-60e6be80-83dc-11ea-9be0-c2e1c3927602.png">
